apiVersion: v1
data:
  script.sh: |-
    #!/bin/bash
    status_code=$(curl -s -o /dev/null -w %{http_code} http://frontendapp.dev.svc.cluster.local)
    if [[ "$status_code" == "200" ]]; then
      echo SPINNAKER_PROPERTY_RELEASE=Success
    else
      echo exit
      exit 0
    fi
kind: ConfigMap
metadata:
  name: script-configmap
  namespace: spinnaker
