---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendapp
  template:
    metadata:
      labels:
        app: frontendapp
    spec:
      hostname: frontendapp
      containers:
      - name: frontendapp
        image: eu.gcr.io/$PROJECT_ID/frontendapp:$SHORT_SHA
        ports:
        - containerPort: 5001
        env:
        - name: APP_QUERY_URL
          valueFrom:
            configMapKeyRef:
              name: frontendapp-env-vars
              key: frontendapp_app_query_url
        - name: APP_SETTINGS_URL
          valueFrom:
            configMapKeyRef:
              name: frontendapp-env-vars
              key: frontendapp_app_settings_url
        - name: APP_SETTINGS_SAVE_URL
          valueFrom:
            configMapKeyRef:
              name: frontendapp-env-vars
              key: frontendapp_app_settings_save_url
      restartPolicy: Always
#         args: ['0.0.0.0', '5001','http://logicapp.dev.svc:5002/logic/query_data','http://cfgmanapp.dev.svc:5004/start','http://cfgmanapp.dev.svc:5004/save']
#       restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontendapp
  labels:
    app: frontendapp
  namespace: dev
spec:
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: frontendapp
  type: LoadBalancer
---
