---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp
  namespace: dev
  labels:
    app: frontendapp
    version: main 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendapp
  template:
    metadata:
      labels:
        app: frontendapp
        version: main
    spec:
      hostname: frontendapp
      containers:
      - name: frontendapp
        image: eu.gcr.io/$PROJECT_ID/frontendapp:$SHORT_SHA
        ports:
        - containerPort: 5001
        env:
        - name: APP_QUERY_URL
          valueFrom:
            configMapKeyRef:
              name: frontendapp-env-vars
              key: app_query_url
        - name: APP_SETTINGS_URL
          valueFrom:
            configMapKeyRef:
              name: frontendapp-env-vars
              key: app_settings_url
        - name: APP_SETTINGS_SAVE_URL
          valueFrom:
            configMapKeyRef:
              name: frontendapp-env-vars
              key: app_settings_save_url
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontendapp
  labels:
    app: frontendapp
    version: main
  namespace: dev
spec:
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: frontendapp
    version: main
  type: LoadBalancer
---
