---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendapp
  template:
    metadata:
      labels:
        app: frontendapp
    spec:
      hostname: frontendapp
      containers:
      - name: frontendapp
        image: eu.gcr.io/$PROJECT_ID/frontendapp:$SHORT_SHA
        ports:
        - containerPort: 5001
        env:
        - name: APP_QUERY_URL
          valueFrom:
            configMapKeyRef:
              name: frontendapp-env-vars
              key: app_query_url
        - name: APP_SETTINGS_URL
          valueFrom:
            configMapKeyRef:
              name: frontendapp-env-vars
              key: app_settings_url
        - name: APP_SETTINGS_SAVE_URL
          valueFrom:
            configMapKeyRef:
              name: frontendapp-env-vars
              key: app_settings_save_url
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontendapp
  labels:
    app: frontendapp
  namespace: dev
spec:
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: frontendapp
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: traderapp-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: traderapp
spec:
  hosts:
  - "*"
  gateways:
  - traderapp-gateway
  http:
  - match:
    - uri:
        prefix: /
    - uri:
        prefix: /hello
#    - uri:
#        prefix: /settings
    route:
    - destination:
        host: frontendapp
        #host: frontendapp.dev.svc
        port:
          number: 5001
