apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: script-job
  name: test-a
  namespace: spinnaker
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - command:
            - bash
            - APP_ADDRESS="http://frontendapp.dev.svc:5001";result=$(curl --connect-timeout 10 -s -o /dev/null -w "%{http_code}" ${APP_ADDRESS});if [ $result == "200" ]; then  echo "Connection succeeded!";fi
          image: tutum/curl
          name: script
          volumeMounts:
            - mountPath: /opt/script
              name: script-configmap
              readOnly: false
      restartPolicy: Never
      serviceAccountName: spinnaker-service-account
      volumes:
        - configMap:
            name: script-configmap
          name: script-configmap
