apiVersion: batch/v1
kind: Job
metadata:
  name: test-a
  namespace: dev
spec:
  template:
    spec:
      containers:
      - name: test-a
        image: tutum/curl
        command: ["/bin/sh", "-c"]
        args: ["curl -s http://frontendapp.dev.svc |grep StockApp || echo fail"]
      restartPolicy: OnFailure
