apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: script-job
  name: test-a
  namespace: dev
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - command:
            - bash
            - /opt/script/script.sh
          image: tutum/curl
          name: script
          volumeMounts:
            - mountPath: /opt/script
              name: script-configmap
              readOnly: false
      restartPolicy: Never
      volumes:
        - configMap:
            name: script-configmap
          name: script-configmap
